export const prompts: string[] = [
  "Sofa shaped like a pineapple, colorful and abstract design",
  "Surrealist painting of a dog playing poker in a dreamy setting",
  "Robots shopping for antiques in Paris, Art Nouveau aesthetic",
  "Digital artwork of a unicorn playing piano in a magical forest",
  "Fox in a lab coat, mixing colorful strange potions, vector art",
  "50mm photograph of two turtles in hot spring, tiny hats, watercolor",
  "Glowing jellyfish swimming in neon underwater world, 3D render",
  "Astronaut enjoying ice cream on the moon, vaporwave art style",
  "Charcoal drawing of a wizard squirrel with magical wand",
  "Stained glass window depicting a pizza with various toppings",
  "Pencil sketch of futuristic city with flying vehicles",
  "Serene lounge with neon-lit pool surrounded by lush plants",
  "Psychic pug reading tarot cards with a giant donut",
  "Koala wearing crown in Renaissance portraiture style",
  "Sad dog in spaceship gazing out window, oil painting",
  "Whale swimming through vibrant field of flowers, painted",
  "Bowl of noodles shaped like a dragon, handmade clay art",
  "Plush robot toy sitting on retro arcade machine",
  "Futuristic city skyline at dusk, neon lights glowing",
  "Two robots holding hands under glowing tree, digital art",
  "Giant ice cream cone floating above forest, 3D render",
  "Superhero riding skateboard, comic book cover design",
  "Colorful fireworks exploding against dark purple sky",
  "Corgi wearing bow tie sitting confidently on a throne",
  "Giant fluffy rabbit standing in golden field at sunrise",
  "Da Vinci's Vitruvian Man reimagined in futuristic armor",
  "Ninja fighting giant octopus in Tokyo, neon-lit streets",
  "Vintage motorcycle racing across desert at sunset, 50mm lens",
  "Realistic portrait of a man with green eyes and red hair",
  "Woman standing before glowing portal to a new world",
  "Pirate ship sailing through cyberpunk city at night",
  "Velociraptor cooking at food truck, chef's outfit",
  "Man wandering through neon-lit streets of Shibuya at night",
  "BBQ that talks, animated style, DreamWorks movie vibes",
  "Cyborg nightclub with lasers and floating platforms, futuristic setting",
  "Lost 1980s sequel to E.T., nostalgic sci-fi design",
  "Taco shaped like diamond, professional food photography",
  "Synthwave owl flying over Cyberpunk Tokyo cityscape",
  "Astronaut discovering mysterious artifact on Mars, sci-fi photography",
  "Dragon flying over Cape Town during colorful sunset",
  "Man falling in love with AI assistant, digital art",
  "Cyborg strolling through New York City at night, lomography style",
  "Frankenstein walking through futuristic Paris at night",
  "Synthwave motorcycle cruising through neon-lit streets",
  "Man exploring glowing streets of Hong Kong at night",
  "Futuristic spaceship soaring above Cape Town, digital render",
];
