export const prompts: string[] = [
  "a sofa in the shape of a pineapple",
  "a surrealist painting by René Magritte of a dog playing poker",
  "robots shopping for antiques in Paris, Art Nouveau style",
  "a digital artwork of a unicorn playing piano in a forest at dawn",
  "a fox in a lab coat mixing strange potions, vector art",
  "a macro 50mm photograph of two turtles in a hot spring, both wearing tiny hats, watercolor effect",
  "3D render of a glowing jellyfish swimming in a neon underwater world",
  "an astronaut eating ice cream on the moon, vaporwave style",
  "a charcoal drawing of a squirrel wearing a wizard hat holding a wand",
  "a stained glass window depicting a pizza with all the toppings",
  "a pencil sketch of a futuristic city with flying trains",
  "a serene lounge with a neon-lit indoor pool surrounded by plants, digital art",
  "a psychic pug reading tarot cards with a giant donut, digital art",
  '"a koala with a crown" in the style of Renaissance portraiture',
  "an oil painting of a sad dog in a spaceship gazing out the window",
  "a painting of a whale swimming through a field of flowers",
  "a bowl of noodles shaped like a dragon, made of clay",
  "A plush toy robot sitting on a retro arcade machine",
  "A neon-lit skyline of a futuristic city at dusk, digital art",
  "Two robots holding hands under a glowing tree, digital art",
  "A 3D render of a giant ice cream cone floating in the sky above a forest",
  "A comic book cover of a superhero riding a skateboard",
  "A colorful explosion of fireworks on a dark purple background",
  "A photo of a Corgi with a bow tie sitting on a throne",
  "A photo of a giant fluffy rabbit standing in a golden field",
  "A photo of Da Vinci's Vitruvian Man wearing futuristic armor",
  "A Ninja fighting a giant octopus in the middle of Tokyo, neon lights",
  "A vintage motorcycle racing through a dusty desert with a sunset, 50mm photography",
  "A realistic photograph of a man with green eyes and red hair",
  "A woman standing in front of a glowing portal to another world",
  "A pirate ship in the middle of a cyberpunk city at night",
  "A velociraptor in a chef’s outfit cooking at a food truck",
  "A man wandering through the streets of Shibuya at night, under neon signs, 50mm lens",
  "A BBQ that can talk, in the style of a DreamWorks animated movie",
  "A futuristic cyborg nightclub with lasers and floating platforms",
  "The lost 1980s sequel to E.T. the Extra-Terrestrial",
  "A taco in the shape of a diamond, professional food photography",
  "A Synthwave Owl, Cyberpunk Tokyo",
  "An astronaut discovering a mysterious artifact on Mars, photography",
  "A Dragon flying over Cape Town at sunset, photography",
  "A Man falling in love with his AI assistant, digital art",
  "A photograph of a cyborg strolling through New York City at night, lomography",
  "Frankenstein walking through a futuristic Paris, black and white photography",
  "Synthwave motorcycle",
  "A man lost in the glowing streets of Hong Kong, illuminated by neon signs, 50mm",
  "A futuristic spaceship flying above Cape Town, digital art",
];
